config/routes.rb
Hushpush::Application.routes.draw do

  root to: 'static_pages#home'
  
  resources :users, only: [:new, :create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :widgets, only: [:create, :destroy, :update]
  resources :widget_preferences, only: [:create, :update]

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/oauth2callback', to: 'widgets#oauthcallback'

  resources :widgets do
    member do
      get 'page'
      get 'load'
      get 'remtask'
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
	@widget = current_user.widgets.build if signed_in?
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="page">
<% if signed_in? %>
<% else %>
	Welcome to HushPush. <%= link_to "Create an account", signup_path %> or <%= link_to "log in", signin_path %> to get started!
<% end %>


<% if signed_in? %>
	<% column_count = 0 %>
	<% for i in 0 .. current_user.widgets.length-2 %>
		<% if column_count > 3 || i == 0 %>
			<% if column_count > 3 %> </div> <% end %>
				<div class="row-fluid">
				<% column_count = 0 %>
				<div class="span3"><%= render 'widgets/widget_display', widget: current_user.widgets[i] %></div>
		<% else %>
				<div class="span3"><%= render 'widgets/widget_display', widget: current_user.widgets[i] %></div>
		<% end %>
		<% column_count += 1 %>
	<% end %>
		</div>
<% end %>
</div>
      <%= debug(params) if Rails.env.development? %>